name: Sabora
description: EduGate
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.22+22

environment:
  sdk: '>=2.19.3 <3.0.0'
#environment:
#  sdk: ">=2.12.0 <3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
#  provider: ^6.0.1
  get: ^4.1.4
  tuple: ^2.0.0
  http: ^0.13.5
  cached_network_image: ^3.1.0
  json_annotation:
  jiffy:
  shared_preferences: ^2.0.6
  visibility_detector: ^0.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #video_player: ^2.5.3
  flutter_svg:
  otp_text_field: ^1.1.3
  flutter_zoom_drawer: ^3.0.4+1
  dots_indicator: ^2.1.0
  carousel_slider: ^4.2.1
  toast: ^0.3.0
  flutter_easyloading: ^3.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.11.0
  firebase_messaging: ^14.6.1
  timer_count_down: ^2.2.2
  persistent_bottom_nav_bar: ^5.0.2
  tab_indicator_styler: ^2.0.0
  video_viewer: ^1.2.7
  native_device_orientation: ^1.1.4
  #flutter_exoplayer: ^0.6.1
  #  flutter_seekbar: ^0.0.1
  percent_indicator: ^4.0.1
#  modal_bottom_sheet: ^2.1.2
  lottie: ^2.3.1
  slide_countdown: ^0.5.0
  just_audio: ^0.9.34
  record: ^4.4.3
  voice_message_package: ^1.0.41
  path_provider: ^2.0.14
  flutter_slidable: ^3.0.0
  image_picker_gallery_camera: ^0.2.2
  dio:
  external_path: ^1.0.3
  permission_handler: ^9.2.0
  url_launcher: ^6.1.10
  flutter_downloader: ^1.10.2
  file_picker:
  wakelock:
#  flutter_screenutil:
  internet_connection_checker: ^1.0.0+1
  flutter_screen_recording: ^2.0.8
#  screenshot_detector:
#  screenshot_callback: ^2.0.3
  flutter_windowmanager: ^0.2.0
  device_info_plus: ^8.2.2
  flutter_local_notifications: ^14.0.0+1
#  flutter_unique_device_id: ^0.0.1
#  audio_session: ^0.1.5
#  flutter_unique_device_id:
  flutter_native_timezone: ^2.0.0
  timezone:
  rxdart: #^0.27.5
  flutter_file_downloader: ^1.1.2
  downloads_path_provider_28 :
  firebase_dynamic_links: ^5.2.0
  share_plus: ^6.3.4
  flutter_html:
  gesture_x_detector: ^1.0.0
  helpers: ^1.2.3
  provider: ^6.0.1
  video_player: ^2.2.6
  volume_watcher: ^2.0.1
  secure_application: ^3.8.0
  flutter_pdfview: ^1.3.1
  flutter_secure_screen: ^0.0.1
  connectivity: ^3.0.6
  dotted_border: ^2.0.0+3
  flutter_keyboard_visibility: ^5.0.3
  rflutter_alert:
  jumping_dot: ^0.0.6



#  custom_rating_bar: ^2.0.5
#  flutter_rating_bar: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/video/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        #        - asset: assets/fonts/Schyler-Italic.ttf
        #          style: italic
        #     - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter_intl:
#  enabled: false
#  arb_dir: lib/l10n
#  output_dir: lib/l10n/generated
#  main_locale: en
#
#flutter_gen:
#  output: lib/utils/gen
#flutter gen-l10n